import Head from "next/head";
import Course from "../components/Course";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import LatestCourse from "../components/LatestCourse";
import LearningHistory from "../components/LearningHistory";
import Niche from "../components/Niche";
import Recommend from "../components/Recommend";

export default function Home() {
  return (
    <div className="overflow-x-hidden min-h-screen min-w-full relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <HeroSection />
        <LearningHistory />
        <Niche />
        <Course />
        <Recommend />
        <LatestCourse />
        <Footer />
    </div>
  );
}
